### ISSUE TITLE
Event encode support

### ISSUE THREAD

**Issue by klauspost** [laurent22/ical-go#1]
Any chance of encode support for events?

**Comment by laurent22** [comment]
Sorry could you clarify what you mean by encode support? You mean supporting text encodings like UTF-8, etc.?

**Comment by klauspost** [comment]
Sorry for the very brief question.

Let me state my case :)

I have a bunch of calendars, and I would like to create a calendar that can be viewed in Outlook as a live updating calendar. I can see there is the Calendar object and I can of course populate it with items - but I see no way to get that out as a iCalendar encoded data.

I guess if it already does this, then just a little documentation would help me a lot.

**Comment by laurent22** [comment]
@klauspost, at the moment, the package doesn't provide this functionality though some of the tools to do it are there. You can use `EncodeTextType` to encode DESCRIPTION and other text fields, `EncodeDateProperty` for dates, and other encoding can be done with built-in Go functions such as `strconv.Itoa`. There is an example in `ICalString()` which takes a `Todo` object and outputs a VTODO.

I think the big missing piece is recurring event support. If you need this, the package doesn't support it so you might have to implement it.
