### ISSUE TITLE
Format code with gofmt

### ISSUE THREAD

**Issue by remast** [laurent22/ical-go#9]
Hi,

is there a reason the code is not formatted using gofmt? I think that would be great because it makes it much easier for others to read the code and submit pull requests.

I would be happy to submit a pull request with all code formatted if you're interested.

Thanks,
Jan

**Comment by laurent22** [comment]
I have no objection to that. Please go ahead and create the pull request.

**Comment by remast** [comment]
Here's the pull request.

**Comment by laurent22** [comment]
Ok thanks, it's merged.
